-- Update badge names to Persian with UTF8MB4 encoding
SET NAMES utf8mb4;

UPDATE badges SET badge_name = 'اولین چت' WHERE badge_key = 'first_chat';
UPDATE badges SET badge_name = 'استاد چت' WHERE badge_key = 'chat_master';
UPDATE badges SET badge_name = 'پروانه اجتماعی' WHERE badge_key = 'social_butterfly';
UPDATE badges SET badge_name = 'محبوب' WHERE badge_key = 'popular';
UPDATE badges SET badge_name = 'جنگجوی هفته' WHERE badge_key = 'streak_7';
UPDATE badges SET badge_name = 'جنگجوی ماه' WHERE badge_key = 'streak_30';
UPDATE badges SET badge_name = 'معرف' WHERE badge_key = 'referrer';
UPDATE badges SET badge_name = 'معرف برتر' WHERE badge_key = 'super_referrer';
UPDATE badges SET badge_name = 'پرنده اولیه' WHERE badge_key = 'early_bird';
UPDATE badges SET badge_name = 'عضو پریمیوم' WHERE badge_key = 'premium';
UPDATE badges SET badge_name = 'کهنه‌کار چت' WHERE badge_key = 'chat_100';
UPDATE badges SET badge_name = 'افسانه چت' WHERE badge_key = 'chat_500';
UPDATE badges SET badge_name = 'استاد پیام' WHERE badge_key = 'message_1000';
UPDATE badges SET badge_name = 'افسانه پیام' WHERE badge_key = 'message_10000';
UPDATE badges SET badge_name = 'لایک‌دهنده' WHERE badge_key = 'like_given_50';
UPDATE badges SET badge_name = 'لایک‌دهنده برتر' WHERE badge_key = 'like_given_200';
UPDATE badges SET badge_name = 'ستاره' WHERE badge_key = 'like_received_1000';
UPDATE badges SET badge_name = 'دنبال‌کننده' WHERE badge_key = 'follow_given_20';
UPDATE badges SET badge_name = 'تأثیرگذار' WHERE badge_key = 'follow_received_50';
UPDATE badges SET badge_name = 'سلبریتی' WHERE badge_key = 'follow_received_200';
UPDATE badges SET badge_name = 'پیام‌رسان' WHERE badge_key = 'dm_sent_50';
UPDATE badges SET badge_name = 'ارتباط‌گر' WHERE badge_key = 'dm_sent_200';
UPDATE badges SET badge_name = 'صدتایی' WHERE badge_key = 'streak_100';
UPDATE badges SET badge_name = 'جنگجوی سال' WHERE badge_key = 'streak_365';
UPDATE badges SET badge_name = 'سفیر' WHERE badge_key = 'referral_50';
UPDATE badges SET badge_name = 'قهرمان' WHERE badge_key = 'referral_100';
UPDATE badges SET badge_name = 'کهنه‌کار پریمیوم' WHERE badge_key = 'premium_1_year';
UPDATE badges SET badge_name = 'استاد پریمیوم' WHERE badge_key = 'premium_lifetime';
UPDATE badges SET badge_name = 'پیشگام' WHERE badge_key = 'early_adopter';
UPDATE badges SET badge_name = 'کاربر فعال' WHERE badge_key = 'active_user';

-- Update achievement names to Persian
UPDATE achievements SET achievement_name = 'اولین چت' WHERE achievement_key = 'first_chat';
UPDATE achievements SET achievement_name = 'چت‌کننده' WHERE achievement_key = 'chat_10';
UPDATE achievements SET achievement_name = 'استاد چت' WHERE achievement_key = 'chat_50';
UPDATE achievements SET achievement_name = 'لایک شده' WHERE achievement_key = 'like_10';
UPDATE achievements SET achievement_name = 'پروانه اجتماعی' WHERE achievement_key = 'like_100';
UPDATE achievements SET achievement_name = 'محبوب' WHERE achievement_key = 'like_500';
UPDATE achievements SET achievement_name = 'جنگجوی هفته' WHERE achievement_key = 'streak_7';
UPDATE achievements SET achievement_name = 'جنگجوی ماه' WHERE achievement_key = 'streak_30';
UPDATE achievements SET achievement_name = 'معرف' WHERE achievement_key = 'referral_1';
UPDATE achievements SET achievement_name = 'معرف برتر' WHERE achievement_key = 'referral_10';
UPDATE achievements SET achievement_name = 'کهنه‌کار چت' WHERE achievement_key = 'chat_100';
UPDATE achievements SET achievement_name = 'افسانه چت' WHERE achievement_key = 'chat_500';
UPDATE achievements SET achievement_name = 'استاد پیام' WHERE achievement_key = 'message_1000';
UPDATE achievements SET achievement_name = 'افسانه پیام' WHERE achievement_key = 'message_10000';
UPDATE achievements SET achievement_name = 'لایک‌دهنده' WHERE achievement_key = 'like_given_50';
UPDATE achievements SET achievement_name = 'لایک‌دهنده برتر' WHERE achievement_key = 'like_given_200';
UPDATE achievements SET achievement_name = 'ستاره' WHERE achievement_key = 'like_received_1000';
UPDATE achievements SET achievement_name = 'دنبال‌کننده' WHERE achievement_key = 'follow_given_20';
UPDATE achievements SET achievement_name = 'تأثیرگذار' WHERE achievement_key = 'follow_received_50';
UPDATE achievements SET achievement_name = 'سلبریتی' WHERE achievement_key = 'follow_received_200';
UPDATE achievements SET achievement_name = 'پیام‌رسان' WHERE achievement_key = 'dm_sent_50';
UPDATE achievements SET achievement_name = 'ارتباط‌گر' WHERE achievement_key = 'dm_sent_200';
UPDATE achievements SET achievement_name = 'صدتایی' WHERE achievement_key = 'streak_100';
UPDATE achievements SET achievement_name = 'جنگجوی سال' WHERE achievement_key = 'streak_365';
UPDATE achievements SET achievement_name = 'سفیر' WHERE achievement_key = 'referral_50';
UPDATE achievements SET achievement_name = 'قهرمان' WHERE achievement_key = 'referral_100';

